local Luna = loadstring(game:HttpGet("https://raw.githubusercontent.com/Nebula-Softworks/Luna-Interface-Suite/master/source.lua"))()

local Window = Luna:CreateWindow({
    Name = "OHIO script",
    Subtitle = "by likegenm",
    MainColor = Color3.fromRGB(30, 215, 96),
    GradientColor = Color3.fromRGB(30, 30, 30),
    GradientEnabled = true,
    AcrylicEnabled = true,
    AcrylicBlur = 0.8,
    AcrylicTransparency = 0.8,
    LoadingTitle = "Loading...",
    LoadingSubtitle = "by Likegenm",
    LoadingEnabled = true,
    LoadingTime = 2,
    Position = UDim2.new(0.5, 0, 0.5, 0),
    Size = UDim2.new(0, 550, 0, 400),
    AutoSize = false,
    MinSize = UDim2.new(0, 500, 0, 350),
    MaxSize = UDim2.new(0, 600, 0, 500),
    Theme = "Dark",
    Roundness = 8,
    ShadowEnabled = true,
    ShadowSize = 10,
    BlurBackground = true,
    CloseKey = Enum.KeyCode.RightAlt,
    Resizable = true,
    Draggable = true,
    AutoShow = true,
    Center = true,
    SaveConfig = true,
    ConfigFolder = "Likegenm OHIO 0101010101010",
})

local LPT = Window:CreateTab({
    Name = "LocalPlayer",
    Icon = "user",
    IconSource = "Material",
    ShowTitle = true,
    GradientIcon = true,
    ImageSource = "rbxassetid://123456789",
    Priority = 1,
})
